ArangoDB-Community/arangodb-net-standard

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
A minor commit to get my first contribution going.
This resolves a warning in the build caused by a an unused property in tests. #9
> Delete unused _dbName property in CursorApiClientTest.

- arangodb-net-standard.Test/ArangoDBNetStandardTest.csproj
Updated the version of XUnit test framework we use in ArangoDBNetStandardTest from 2.4.0 to 2.4.1. #17
> Update XUnit from 2.4.0 to 2.4.1.

- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs
- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTestFixture.cs
- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard.Test/TransactionApi/TransactionApiClientTest.cs
- arangodb-net-standard/CollectionApi/CollectionApiClient.cs
- arangodb-net-standard/CollectionApi/TruncateCollectionResult.cs
- project/roadmap.md
#25 Add tests for Truncate Collection
Also implemented TruncateCollectionResponse model to capture the properties returned by this endpoint.
> #25 Add tests for Truncate Collection

- arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTest.cs
- arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTestFixture.cs
- arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs
- arangodb-net-standard/DatabaseApi/ListDatabaseResult.cs
- arangodb-net-standard/Transport/Http/HttpApiTransport.cs
- project/roadmap.md
> Add database API endpoints to retrieve the list of databases.

- arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
- arangodb-net-standard.Test/GraphApi/GraphApiClientTestFixture.cs
- arangodb-net-standard/GraphApi/PostGraphBody.cs
> Allow test to pass for ArangoDB versions affected by a bug in the PutGraphEdgeDefinition endpoint.

- arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs
- arangodb-net-standard/Serialization/CamelCasePropertyNamesExceptDictionaryContractResolver.cs
- arangodb-net-standard/Serialization/DictionaryValueConverter.cs
- arangodb-net-standard/Serialization/JsonNetApiClientSerialization.cs
bug/#189
This prevents camel-casing or ignoring null values for user-specified
values used for cursor request bindVars or transaction params.
> Introduce special handling for dictionary serialization

- arangodb-net-standard.Test/ArangoDBNetStandardTest.csproj
- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs
- arangodb-net-standard/CollectionApi/CollectionApiClient.cs
fix #208
The api path variable was used for the request. Passing the query string variable instead solved the issue.
I added a test to verify that the query string is built properly. To mock the transport layer, I added a dependency to the [Moq package](https://www.nuget.org/packages/moq/).
> Use query string in PostCollectionAsync.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/DocumentBase.cs
- arangodb-net-standard/DocumentApi/Models/PostDocumentsQuery.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentQuery.cs
fix #229
Add a separate class to hold the query parameters of the `PutDocumentAsync` method.
I also thought about adding the property to the existing `PutDocumentsQuery` with a comment to indicate it's used only for `PutDocumentAsync` (single document).
But I think creating a dedicated class is cleaner and more in line with the other APIs.
> Add a class for query parameters of PutDocumentAsync.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/DeleteDocumentsResponse.cs
- arangodb-net-standard/DocumentApi/Models/PostDocumentsResponse.cs
fix #233
Don't deserialize response if silent `query` parameter is true for `PostDocumentsAsync` and `DeleteDocumentsAsync`, instead return an empty list.
> Return empty response when silent is true.

- arangodb-net-standard/ApiClientBase.cs
fix #231
Also wrapped the document ID into quotes "".
> Cleanup document ID validation message.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentsDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentsResponse.cs
fix #220
- Create a new response model for PUT document endpoints, in line with other endpoints
- Use the existing `DocumentBase` model when possible
- Update tests
- Add missing comments to other similar response models
> Add new model with _oldRev for PUT document endpoints.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/DeleteDocumentQuery.cs
fix #230
I kept the `Silent` parameter in `DeleteDocumentsQuery` because it works, it was probably not documented by mistake.
Also:
- added tests for query parameters of `DeleteDocumentAsync` and `DeleteDocumentsAsync`.
- grouped `DeleteDocumentAsync` and `DeleteDocumentsAsync` methods together in the file
> Add a class for query parameters of DeleteDocumentAsync.

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
- arangodb-net-standard/CursorApi/Models/PostCursorBody.cs
- arangodb-net-standard/CursorApi/Models/PostCursorOptions.cs
#246
https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html
I have tested that this new option works when provided. I used something like this:
```csharp
PostCursorAsync<object>("FOR i IN 1..1000000 RETURN { iteration: CONCAT("iteration ", i) }",
new Dictionary<string, object> { },
new PostCursorOptions
{
MaxRuntime = 1
})
```
> Add support for maxRuntime cursor option.

- arangodb-net-standard/AqlFunctionApi/AqlFunctionApiClient.cs
- arangodb-net-standard/ArangoDBClient.cs
- arangodb-net-standard/AuthApi/AuthApiClient.cs
- arangodb-net-standard/CollectionApi/CollectionApiClient.cs
- arangodb-net-standard/CursorApi/CursorApiClient.cs
- arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/TransactionApi/TransactionApiClient.cs
- arangodb-net-standard/UserApi/UserApiClient.cs
fix #206
Changes:
- Make public methods `virtual`
- Change private transport client and API path to protected
It would also be beneficial to allow extending the `HttpApiTransport` but I think that deserves its own issue/pull request.
> Make client APIs extensible.

- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
fix #252
`IDocumentApiClient` is the only one in which I found missing methods.
> Add missing methods in IDocumentApiClient.

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
- arangodb-net-standard/ApiClientBase.cs
- arangodb-net-standard/Serialization/SerializationException.cs
See https://github.com/Actify-Inc/arangodb-net-standard/issues/274 for more details on the origin of this improvement
> Create and throw dedicated serialization exception.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/DeleteDocumentsResponse.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentsDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentsResponse.cs
- arangodb-net-standard/DocumentApi/Models/PostDocumentsQuery.cs
- arangodb-net-standard/DocumentApi/Models/PostDocumentsResponse.cs
fix #269
Quite close to #268 but that pull request was already up when I discovered that `_oldRev` was also missing.
> Add _oldRev property in PatchDocumentsResponse.

- arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
- arangodb-net-standard/DocumentApi/Models/DeleteDocumentsDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentsDocumentResponse.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentsDocumentResponse.cs
- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/GraphApi/IGraphApiClient.cs
fix #266
I pulled a couple of changes from #270 and #268, please review/merge those first.
- Use `T` for body and `U` for response in `GraphApiClient.PatchEdgeAsync<T, U>` (that was the only one inconsistent)
- Use `T` instead of `U` for type name in response models
- Add comments on related response models
> Fix inconsistent usage of T and U types for body and response.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentsQuery.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentsResponse.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentsQuery.cs
fix #273 
Updated `PatchDocumentsQuery` and `PutDocumentsQuery` to include a `Silent` parameter. Updated endpoint methods accordingly + related unit tests.
> Add missing silent parameter in query models for multiple documents

- arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
- arangodb-net-standard/ApiClientBase.cs
- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/GraphApi/IGraphApiClient.cs
fix #146
Contains changes from #271, please review/merge first.
> Add method overloads with document ID.

- arangodb-net-standard.Test/UserApi/UserApiClientTest.cs
- arangodb-net-standard/UserApi/IUserApiClient.cs
- arangodb-net-standard/UserApi/Models/GetUserResponse.cs
- arangodb-net-standard/UserApi/Models/PatchUserBody.cs
- arangodb-net-standard/UserApi/Models/PatchUserResponse.cs
- arangodb-net-standard/UserApi/Models/PostUserResponse.cs
- arangodb-net-standard/UserApi/Models/PutUserBody.cs
- arangodb-net-standard/UserApi/Models/PutUserResponse.cs
- arangodb-net-standard/UserApi/Models/UserResponseBase.cs
- arangodb-net-standard/UserApi/UserApiClient.cs
fix #277
- Added the following methods in `UserApiClient`: `PutUserAsync`, `PatchUserAsync` and `GetUserAsync`.
- Added related data models for body and response + `UserResponseBase` which contains the base properties common to GET, POST, PUT, PATCH responses.
- Also added related unit tests.
> Implement remaining CRUD operation for user API.

- arangodb-net-standard.Test/UserApi/UserApiClientTest.cs
- arangodb-net-standard.Test/UserApi/UserApiClientTestFixture.cs
- arangodb-net-standard/UserApi/IUserApiClient.cs
- arangodb-net-standard/UserApi/Models/DeleteAccessLevelResponse.cs
- arangodb-net-standard/UserApi/Models/DeleteUserResponse.cs
- arangodb-net-standard/UserApi/Models/GetAccessLevelResponse.cs
- arangodb-net-standard/UserApi/Models/GetAccessibleDatabasesQuery.cs
- arangodb-net-standard/UserApi/Models/GetAccessibleDatabasesResponse.cs
- arangodb-net-standard/UserApi/Models/PutAccessLevelBody.cs
- arangodb-net-standard/UserApi/Models/PutAccessLevelResponse.cs
- arangodb-net-standard/UserApi/Models/ResponseBase.cs
- arangodb-net-standard/UserApi/Models/UserResponseBase.cs
- arangodb-net-standard/UserApi/UserApiClient.cs
fix #282
Implemented the following methods:
- PutDatabaseAccessLevelAsync
- GetDatabaseAccessLevelAsync
- DeleteDatabaseAccessLevelAsync
- GetAccessibleDatabasesAsync
- PutCollectionAccessLevelAsync
- GetCollectionAccessLevelAsync
- DeleteCollectionAccessLevelAsync
Also added related data models and unit tests.
I would like to draw attention on the following endpoint: `GET /_api/user/{user}/database/`, represented by `GetAccessibleDatabasesAsync` and the response `GetAccessibleDatabasesResponse`.
https://www.arangodb.com/docs/stable/http/user-management.html#list-the-accessible-databases-for-a-user
The type of the values in the `result` property of the response will change if the query parameter `full` is provided.
Example without full:
```
"result" : { 
"_system" : "rw" 
} 
```
Example …
> Implement access level methods in UserApiClient.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard.Test/DocumentApi/Models/PostDocumentMockModel.cs
- arangodb-net-standard.Test/DocumentApi/Models/PostDocumentMockModelNew.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
fix #304
Add overload `PostDocumentAsync<T, U>`
> Add a PostDocumentAsync with extra generic for new doc type.

- .circleci/config.yml
- arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/GraphApi/Models/GraphResult.cs
- arangodb-net-standard/GraphApi/Models/PostGraphBody.cs
- arangodb-net-standard/GraphApi/Models/PostGraphOptions.cs
> Make cluster-only graph properties optional in response.

- arangodb-net-standard.Test/UserApi/UserApiClientTest.cs
- arangodb-net-standard/UserApi/IUserApiClient.cs
- arangodb-net-standard/UserApi/Models/AvailableUser.cs
- arangodb-net-standard/UserApi/Models/GetUsersResponse.cs
- arangodb-net-standard/UserApi/UserApiClient.cs
fix #258
Implement remaining endpoint:
- List available Users `GET /_api/user/`
https://www.arangodb.com/docs/stable/http/user-management.html#list-available-users
> Implement endpoint to list available users in UserApiClient.

- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs
- arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
- arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs
- arangodb-net-standard.Test/Serialization/Models/TestModel.cs
- arangodb-net-standard/CollectionApi/Models/CollectionType.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionCountResponse.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionFiguresResponse.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionPropertiesResponse.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionResponse.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionRevisionResponse.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionsResponseResult.cs
- arangodb-net-standard/CollectionApi/Models/PostCollectionBody.cs
- arangodb-net-standard/CollectionApi/Models/PostCollectionResponse.cs
- arangodb-net-standard/CollectionApi/Models/PutCollectionPropertyResponse.cs
- arangodb-net-standard/CollectionApi/Models/RenameCollectionResponse.cs
- arangodb-net-standard/CollectionApi/Models/TruncateCollectionResponse.cs
- arangodb-net-standard/Serialization/ApiClientSerialization.cs
- arangodb-net-standard/Serialization/ApiClientSerializationOptions.cs
- arangodb-net-standard/Serialization/JsonNetApiClientSerialization.cs
> Change collection `Type` property from integer to enum value.

- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs
- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
fix #318
Also remove remaining sync waiting of async tasks.
> Implement IAsyncLifetime in test classes with async calls in constructor.

- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs
- arangodb-net-standard/CollectionApi/Models/GetCollectionPropertiesResponse.cs
- arangodb-net-standard/CollectionApi/Models/PostCollectionBody.cs
> Fix ShardKeys property by using collection type instead of string.

- .circleci/config.yml
- arangodb-net-standard.Test/TransactionApi/TransactionApiClientTest.cs
- arangodb-net-standard/TransactionApi/ITransactionApiClient.cs
- arangodb-net-standard/TransactionApi/Models/PostTransactionBody.cs
- arangodb-net-standard/TransactionApi/Models/StreamTransactionBody.cs
- arangodb-net-standard/TransactionApi/Models/StreamTransactionResponse.cs
- arangodb-net-standard/TransactionApi/Models/StreamTransactionResult.cs
- arangodb-net-standard/TransactionApi/Models/StreamTransactionStatus.cs
- arangodb-net-standard/TransactionApi/Models/StreamTransactions.cs
- arangodb-net-standard/TransactionApi/Models/Transaction.cs
- arangodb-net-standard/TransactionApi/TransactionApiClient.cs
Implemented the Stream Transaction Api using the documentation from Arangodb
https://www.arangodb.com/docs/3.6/http/transaction-stream-transaction.html
Even though the API calls work, the collections gets updated once the transactions begins (or) before committing/aborting.
Added few test cases to check that.
> Implement Stream Transaction Api.

- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
- arangodb-net-standard/DocumentApi/Models/DocumentHeaderProperties.cs
fix #330
Used rename tool in Visual Studio and renamed the file.
> Rename header class of document API for consistency.

- readme.md
> Mention usage of http request headers in readme.

- arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs
- arangodb-net-standard.Test/Serialization/Models/InnerTestModel.cs
- arangodb-net-standard.Test/Serialization/Models/TestModel.cs
This is to give a clearer view of what to expect when serializing with default options.
> Extend coverage of default serialization logic.

- arangodb-net-standard/CursorApi/ICursorApiClient.cs
> Make header properties optional in cursor API client interface.

- .circleci/config.yml
> Update CI config to run tests against ArangoDB 3.9

- ChangeLog.md
Add changelog file to log project updates.
> Add changelog file

- arangodb-net-standard/Transport/Http/HttpApiTransport.cs
- If a database name is not provided for a particular API operation, default the database name to _system.
- Add support for Oasis SSL certificates
> Support for Oasis 

- arangodb-net-standard/AnalyzerApi/Models/Analyzer.cs
- arangodb-net-standard/AnalyzerApi/Models/AnalyzerProperties.cs
- arangodb-net-standard/IndexApi/Models/IndexResponseBase.cs
- arangodb-net-standard/TransactionApi/Models/PostTransactionResponse.cs
fix #372
The warnings listed on the issue have been resolved.
> Resolve build warnings caused by syntax issues in XML doc comments.

- arangodb-net-standard.Test/AnalyzerApi/AnalyzerApiClientTest.cs
- arangodb-net-standard.Test/AnalyzerApi/AnalyzerApiClientTestFixture.cs
- arangodb-net-standard.Test/IndexApi/IndexApiClientTestFixture.cs
- arangodb-net-standard/CollectionApi/Models/PostCollectionResponse.cs
- arangodb-net-standard/DatabaseApi/Models/GetDatabaseInfoResponse.cs
- arangodb-net-standard/IndexApi/Models/ResponseBase.cs
Also fix namespace of View API test classes.
May catch/cause conflicts from/for #376
> Simplify error handling in test fixture of Index API client

- .circleci/config.yml
- arangodb-net-standard.Test/AdminApi/AdminApiClientTest.cs
- arangodb-net-standard.Test/AdminApi/AdminApiClientTestFixture.cs
- arangodb-net-standard/AdminApi/AdminApiClient.cs
- arangodb-net-standard/AdminApi/IAdminApiClient.cs
- arangodb-net-standard/AdminApi/Models/EngineAlias.cs
- arangodb-net-standard/AdminApi/Models/EngineAliasIndex.cs
- arangodb-net-standard/AdminApi/Models/EngineSupports.cs
- arangodb-net-standard/AdminApi/Models/GetLogsQuery.cs
- arangodb-net-standard/AdminApi/Models/GetLogsResponse.cs
- arangodb-net-standard/AdminApi/Models/GetServerEngineTypeResponse.cs
- arangodb-net-standard/AdminApi/Models/GetServerIdResponse.cs
- arangodb-net-standard/AdminApi/Models/GetServerRoleResponse.cs
- arangodb-net-standard/AdminApi/Models/GetServerVersionQuery.cs
- arangodb-net-standard/AdminApi/Models/GetServerVersionResponse.cs
- arangodb-net-standard/AdminApi/Models/LogLevel.cs
- arangodb-net-standard/AdminApi/Models/LogMessage.cs
- arangodb-net-standard/AdminApi/Models/ResponseBase.cs
- arangodb-net-standard/ArangoDBClient.cs
- arangodb-net-standard/IArangoDBClient.cs
- project/roadmap.md
`GET/_admin/log/entries` Read global logs from the server
`POST/_admin/routing/reload` Reloads the routing information
`GET/_admin/server/id` Return id of a server in a cluster
`GET/_admin/server/role` Return role of a server in a cluster
`GET/_api/engine` Return server database engine type
`GET/_api/version` Return server version
> Support basic Admin API

- arangodb-net-standard.Test/IndexApi/IndexApiClientTest.cs
- arangodb-net-standard.Test/IndexApi/IndexApiClientTestFixture.cs
- arangodb-net-standard/AqlFunctionApi/Models/PostExplainAqlQueryResponseIndex.cs
- arangodb-net-standard/IndexApi/IIndexApiClient.cs
- arangodb-net-standard/IndexApi/IndexApiClient.cs
- arangodb-net-standard/IndexApi/Models/IndexResponseBase.cs
- arangodb-net-standard/IndexApi/Models/IndexTypes.cs
- arangodb-net-standard/IndexApi/Models/PostIndexBody.cs
fix #375
@tjoubert @Zyqsempai  @rossmills99 What do you think of this approach?
> Use constants to represent index types.

- arangodb-net-standard.Test/BulkOperationsApi/BulkOperationsApiClientTest.cs
- arangodb-net-standard.Test/BulkOperationsApi/BulkOperationsApiClientTestFixture.cs
- arangodb-net-standard/ApiClientBase.cs
- arangodb-net-standard/ArangoDBClient.cs
- arangodb-net-standard/BulkOperationsApi/BulkOperationsApiClient.cs
- arangodb-net-standard/BulkOperationsApi/IBulkOperationsApiClient.cs
- arangodb-net-standard/BulkOperationsApi/Models/ImportDocumentArraysBody.cs
- arangodb-net-standard/BulkOperationsApi/Models/ImportDocumentObjectsBody.cs
- arangodb-net-standard/BulkOperationsApi/Models/ImportDocumentsOnDuplicate.cs
- arangodb-net-standard/BulkOperationsApi/Models/ImportDocumentsQuery.cs
- arangodb-net-standard/BulkOperationsApi/Models/ImportDocumentsResponse.cs
- arangodb-net-standard/IArangoDBClient.cs
- arangodb-net-standard/Serialization/ApiClientSerialization.cs
- arangodb-net-standard/Serialization/IApiClientSerialization.cs
- arangodb-net-standard/Serialization/JsonNetApiClientSerialization.cs
- project/roadmap.md
Contains the following updates:
1. Adds support for bulk operations endpoints:
POST: /_api/import#document : imports document values
POST: /_api/import#json: imports documents from JSON
2. Roadmap doc - to reflect current state of development
3. Added SerializeToString() method to JsonNetApiClientSerialization.cs to support serializing an object to a simple JSON string. This is necessary because sometimes the bulk operations endpoints expects a non-standard JSON body (for example JSON objects or arrays separated by newline character). In such cases, it's necessary to serialize each object in the list and add them to the body separated by the new line character. We may change this in the future based on performance tests to identify the best way to deal with this.
> Bulk operations support

- ChangeLog.md
Updated changelog with features merged on 16/05 and 24/05
> Updated ChangeLog

- ChangeLog.md
- arangodb-net-standard/ArangoDBNetStandard.csproj
- contributing.md
Amended csproj, contributing.md and contributing.md
> Updated pre-release items

- arangodb-net-standard/BulkOperationsApi/BulkOperationsApiClient.cs
`ConfigureAwait(false)` should be applied at all async call levels to make sure none of them resume on a captured synchronization context.
Source: https://stackoverflow.com/a/57055739
> Apply ConfigureAwait(false) to inner method calls of bulk operations API

- readme.md
fix #367
I also mentioned why those values were chosen as default because it's come up in some discussions with the team I work with.
> Mention default values of serialization options in readme.

- arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs
- arangodb-net-standard/Serialization/ApiClientSerialization.cs
fix #388
The property `DefaultOptions` was creating a new instance of `ApiClientSerializationOptions` each time it was accessed. I have modified the property to not return a new instance every time it is accessed. A new unit test was added to cover this behavior.
> Fix modifying default serialization options.

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
- arangodb-net-standard/CursorApi/CursorApiClient.cs
- arangodb-net-standard/CursorApi/ICursorApiClient.cs
- arangodb-net-standard/CursorApi/Models/PostCursorResponse.cs
Rename CursorResponse to PostCursorResponse for consistency
Refer to issue #339
> Breaking Change: Renamed CursorResponse to PostCursorResponse

- arangodb-net-standard/Serialization/ApiClientSerialization.cs
- arangodb-net-standard/Serialization/ApiClientSerializationOptions.cs
- arangodb-net-standard/Serialization/JsonNetApiClientSerialization.cs
- readme.md
Solves #213 
- Added ApiClientSerializationOptions.IgnoreMissingMember (true by default)
- Set JsonSerializerSettings.MissingMemberHandling in JsonNetApiClientSerialization based on value in ApiClientSerializationOptions.IgnoreMissingMember
> Make missing member handling configurable

- arangodb-net-standard/ApiErrorException.cs
Solves #320 
Checks for null before accessing the ErrorMessage property
> Solves NullReferenceException thrown when deserializing empty content of error reponse

- project/roadmap.md
> Updated roadmap doc

- arangodb-net-standard/ApiHeaderProperties.cs
- arangodb-net-standard/CollectionApi/CollectionApiClient.cs
- arangodb-net-standard/CollectionApi/ICollectionApiClient.cs
- arangodb-net-standard/CollectionApi/Models/CollectionHeaderProperties.cs
- arangodb-net-standard/CursorApi/Models/CursorHeaderProperties.cs
- arangodb-net-standard/DocumentApi/Models/DocumentHeaderProperties.cs
- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/GraphApi/IGraphApiClient.cs
- arangodb-net-standard/GraphApi/Models/GraphHeaderProperties.cs
Solves issue #328 
- Added ApiHeaderProperties allowing users to pass any header (as long as it is supported) to a method. This will be useful for situations in the future where the API adds new headers and we have not had the time to add named properties/parameters for these new headers in the driver.
- Added stream transaction support in the Collection and Graph APIs
> Stream transaction support in the Collection and Graph APIs

- arangodb-net-standard.Test/IndexApi/IndexApiClientTest.cs
- arangodb-net-standard.Test/IndexApi/IndexApiClientTestFixture.cs
- arangodb-net-standard/AqlFunctionApi/Models/PostExplainAqlQueryResponseIndex.cs
- arangodb-net-standard/IndexApi/IIndexApiClient.cs
- arangodb-net-standard/IndexApi/IndexApiClient.cs
- arangodb-net-standard/IndexApi/Models/IIndexResponse.cs
- arangodb-net-standard/IndexApi/Models/IndexResponseBase.cs
- arangodb-net-standard/IndexApi/Models/IndexTypes.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexField.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexSort.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexSortItem.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexStoredValue.cs
- arangodb-net-standard/IndexApi/Models/PostFulltextIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostGeoSpatialIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostHashIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostInvertedIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostMultiDimensionalIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostPersistentIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostSkiplistIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostTTLIndexBody.cs
1) Use separate async methods to POST different index types. This way when one type of deprecated, we can simply deprecate the method. Fulltext is deprecated in 3.10.
2) Index cache: added CacheEnabled property for persistent indexes. Introduced in 3.10.
3) Index stored values: added StoredValues property for persistent indexes. Introduced in 3.10.
4) Deprecate fulltext index in 3.10.
5) Geo index legacyPolygons: added legacyPolygons property. Introduced in 3.10.
6) Added InvertedIndex support for ArangoSearch. 
Note that documentation has not been finalized. Once it is, we will update code documentation on the several classes and properties involved.
ArangoDB 3.10 Index API changes: https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#index-api
> 3.10: Consolidation of new 3.10 index features

- arangodb-net-standard/ApiHeaderProperties.cs
- arangodb-net-standard/CursorApi/CursorApiClient.cs
- arangodb-net-standard/CursorApi/ICursorApiClient.cs
- arangodb-net-standard/CustomHttpHeaders.cs
- arangodb-net-standard/DocumentApi/DocumentApiClient.cs
- arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
- arangodb-net-standard/TransactionApi/ITransactionApiClient.cs
- arangodb-net-standard/TransactionApi/TransactionApiClient.cs
Added Read From Follower support to the following:
- Single document reads (GET /_api/document)
- Batch document reads (PUT /_api/document?onlyget=true)
- Read-only AQL queries (POST /_api/cursor)
- Read-only Stream Transactions and their sub-operations (POST /_api/transaction/begin)
See also https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#read-from-followers
> 3.10: Added Read From Follower support

- .circleci/config.yml
- arangodb-net-standard.Test/AdminApi/AdminApiClientTestFixture.cs
- arangodb-net-standard.Test/AnalyzerApi/AnalyzerApiClientTestFixture.cs
- arangodb-net-standard.Test/ApiClientTestFixtureBase.cs
- arangodb-net-standard.Test/AqlFunctionApi/AqlFunctionApiClientTestFixture.cs
- arangodb-net-standard.Test/BulkOperationsApi/BulkOperationsApiClientTestFixture.cs
- arangodb-net-standard.Test/CollectionApi/CollectionApiClientTestFixture.cs
- arangodb-net-standard.Test/CursorApi/CursorApiClientTestFixture.cs
- arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTestFixture.cs
- arangodb-net-standard.Test/DocumentApi/DocumentApiClientTestFixture.cs
- arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
- arangodb-net-standard.Test/GraphApi/GraphApiClientTestFixture.cs
- arangodb-net-standard.Test/IndexApi/IndexApiClientTestFixture.cs
- arangodb-net-standard.Test/TransactionApi/TransactionApiClientTestFixture.cs
- arangodb-net-standard.Test/UserApi/UserApiClientTestFixture.cs
- arangodb-net-standard.Test/ViewApi/ViewApiClientTestFixture.cs
Added test-arangodb-3_10 in CircleCI workflow.
> Added test-arangodb-3_10 in CircleCI workflow.

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
- arangodb-net-standard/CursorApi/CursorApiClient.cs
- arangodb-net-standard/CursorApi/ICursorApiClient.cs
- arangodb-net-standard/CursorApi/Models/CursorResponse.cs
This reverts commit [ddecb1c7e038b8b9bf8f65ae4b59363f711eb15e](https://github.com/ArangoDB-Community/arangodb-net-standard/pull/387/commits/ddecb1c7e038b8b9bf8f65ae4b59363f711eb15e).
This is a breaking change that we agreed to revert temporarily.
> Revert "Renamed CursorResponse to PostCursorResponse"

- arangodb-net-standard/ArangoDBNetStandard.csproj
Reverts ArangoDB-Community/arangodb-net-standard#384
This is a breaking change that we agreed to revert temporarily.
> Revert "Bump Newtonsoft.Json from 12.0.2 to 13.0.1 in /arangodb-net-standard"

- readme.md
Solves #183 
Added 1 example of how to use graph, vertices and edges in a simple case. See https://github.com/ArangoDB-Community/arangodb-net-standard/blob/feature-3.8/DE-286-graph-get-started/readme.md#example-using-graphs
> Added example using graphs, vertices and edges

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
- arangodb-net-standard/CursorApi/CursorApiClient.cs
- arangodb-net-standard/CursorApi/ICursorApiClient.cs
- arangodb-net-standard/CursorApi/Models/CursorResponse.cs
Rename was necessary to fix issues caused by PR#396
> Renamed PostCursorResponse to CursorResponse

- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/GraphApi/IGraphApiClient.cs
Not sure if we want to do more to preserve backwards compatibility, but I guess the most common use case is to not specify these parameters which then shouldn't make this breaking. But I'll leave that to you to decide!
> Fixes #426 Impossible to specify ApiClientSerializationOptions when patching an edge

- .gitignore
- arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs
- arangodb-net-standard/Serialization/ApiClientSerialization.cs
- arangodb-net-standard/Serialization/ApiClientSerializationOptions.cs
- arangodb-net-standard/Serialization/CamelCasePropertyNamesExceptDictionaryContractResolver.cs
- arangodb-net-standard/Serialization/DictionaryValueConverter.cs
- arangodb-net-standard/Serialization/JsonNetApiClientSerialization.cs
Solved Issue #400 
Amended the code to pass ApiClientSerializationOptions to DictionaryValueConverter
> Fixed dictionary item value serialization issue

- arangodb-net-standard/CustomHttpHeaders.cs
- arangodb-net-standard/DriverConstants.cs
- arangodb-net-standard/Transport/Http/HttpApiTransport.cs
- arangodb-net-standard/Transport/IApiClientTransport.cs
See related issue for more information regarding requirements.
Added driver info header in HttpApiTransport.ApplyHeaders()
> Added header for driver version and other info

- arangodb-net-standard/AnalyzerApi/Models/AnalyzerProperties.cs
- arangodb-net-standard/AnalyzerApi/Models/GeoJSONAnalyzerOptions.cs
- arangodb-net-standard/AnalyzerApi/Models/TextAnalyzerEdgeNgram.cs
Added missing `ngram` properties
Solves issue #442
> Added missing ngram properties

- arangodb-net-standard/AqlFunctionApi/AqlFunctionApiClient.cs
- arangodb-net-standard/ViewApi/ViewsApiClient.cs
Forward missed CancellationTokens from API to IApiClientTransport calls
> Forward missed CancellationTokens

- arangodb-net-standard/ArangoDBErrors.cs
Solves issue #424 
Added an enum of ArangoDB errors.
> Added ArangoDBErrors enum

- arangodb-net-standard/DocumentApi/Models/DeleteDocumentQuery.cs
- arangodb-net-standard/DocumentApi/Models/DeleteDocumentsQuery.cs
- arangodb-net-standard/DocumentApi/Models/OverwriteModes.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentQuery.cs
- arangodb-net-standard/DocumentApi/Models/PatchDocumentsQuery.cs
- arangodb-net-standard/DocumentApi/Models/PostDocumentsQuery.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentQuery.cs
- arangodb-net-standard/DocumentApi/Models/PutDocumentsQuery.cs
- Fixes #255 
- Add missing properties to Post, Put and Patch document query objects
- Updated the query objects as per specifications here: https://www.arangodb.com/docs/stable/http/document-working-with-documents.html#update-document
> Add missing properties to Post, Put and Patch document query objects

- arangodb-net-standard/GraphApi/GraphApiClient.cs
- arangodb-net-standard/GraphApi/Models/PostGraphBody.cs
- arangodb-net-standard/GraphApi/Models/PostGraphOptions.cs
- arangodb-net-standard/GraphApi/Models/PostNonSatelliteGraphOptions.cs
- arangodb-net-standard/GraphApi/Models/PostSatelliteGraphOptions.cs
Solves issue #306 
- Added PostSatelliteGraphOptions and PostNonSatelliteGraphOptions inheriting from PostGraphOptions.
- Declared PostGraphOptions abstract so it cannot be instantiated. This is a breaking change!
- Added IsDisjoint to PostGraphBody
- Added WriteConcern and Satellites to PostGraphOptions
> Added support for satellite graphs in graph API

- arangodb-net-standard/AnalyzerApi/Models/AnalyzerFeatures.cs
- arangodb-net-standard/IndexApi/IIndexApiClient.cs
- arangodb-net-standard/IndexApi/IndexApiClient.cs
- arangodb-net-standard/IndexApi/Models/CompressionTypes.cs
- arangodb-net-standard/IndexApi/Models/IInvertedIndex.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexConsolidationPolicy.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexField.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexResponse.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexSort.cs
- arangodb-net-standard/IndexApi/Models/InvertedIndexStoredValue.cs
- arangodb-net-standard/IndexApi/Models/PostIndexBody.cs
- arangodb-net-standard/IndexApi/Models/PostInvertedIndexBody.cs
- Added InvertedIndexResponse (a breaking change).
- Added missing comments on PostInvertedIndexBody and associated classes.
Solves issue #443
> Fixed PostInvertedIndexAsync() response issue

- arangodb-net-standard/IndexApi/Models/InvertedIndexConsolidationPolicy.cs
Fix the property type for SegmentsBytesMax.  `int` cannot contain the default value.  This should help further resolve #470.
> Fix InvertedIndexConsolidationPolicy. SetgmentsBytesMax type

- .circleci/config.yml
- arangodb-net-standard.Test/ArangoDBNetStandardTest.csproj
> Use latest stable LTS .NET SDK to run tests (.NET 8)

- .circleci/config.yml
- arangodb-net-standard.Test/ViewApi/ViewApiClientTest.cs
#479  Adds tests for ArangoDB 3.11
> Fix #479 Add tests for ArangoDB 3.11.

- arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs
- arangodb-net-standard.Test/CursorApi/CursorApiClientTestFixture.cs
- arangodb-net-standard/CursorApi/CursorApiClient.cs
- arangodb-net-standard/CursorApi/ICursorApiClient.cs
- arangodb-net-standard/CursorApi/Models/CursorResponse.cs
- arangodb-net-standard/CursorApi/Models/CursorResponseBase.cs
I propose overloading **CursorApi.PostCursorAsync** to enable the execution of ad-hoc queries and return only basic statistics.
> Overload CursorApi.PostCursorAsync to execute ad-hoc queries and return only basic statistics

- arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs
- arangodb-net-standard.Test/TransactionApi/TransactionApiClientTest.cs
- arangodb-net-standard/TransactionApi/ITransactionApiClient.cs
- arangodb-net-standard/TransactionApi/Models/PostTransactionBody.cs
- arangodb-net-standard/TransactionApi/TransactionApiClient.cs
> Mark PostTransactionAsync as deprecated since ArangoDB 3.12
