ArangoDB-Community/arangodb-net-standard

arangodb-net-standard.Test/ApiClientTestFixtureBase.cs, arangodb-net-standard.Test/ArangoDBNetStandardTest.csproj, arangodb-net-standard.Test/CollectionApi/CollectionApiClientTestFixture.cs, arangodb-net-standard.Test/CursorApi/CursorApiClientTestFixture.cs, arangodb-net-standard.Test/DocumentApi/DocumentApiClientTestFixture.cs, arangodb-net-standard.Test/TransactionApi/TransactionApiClientTestFixture.cs
=> Implement IAsyncLifeTime to support async test fixtures.

arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs, arangodb-net-standard/CollectionApi/CollectionApiClient.cs, arangodb-net-standard/CollectionApi/DeleteCollectionResponse.cs, project/roadmap.md
#8 Add tests for Delete Collection Async.
Also re-implemented the Delete collection response model to reflect the properties the REST API returns in the response.
=> Feature/#8 Add tests for Delete Collection Async

contributing.md
=> Add contribution doc

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/GraphApiClientTestFixture.cs, arangodb-net-standard/ArangoDBClient.cs, arangodb-net-standard/ArangoDBNetStandard.csproj, arangodb-net-standard/GraphApi/EdgeDefinition.cs, arangodb-net-standard/GraphApi/GetGraphsGraphResult.cs, arangodb-net-standard/GraphApi/GetGraphsResult.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PostGraphBody.cs, arangodb-net-standard/GraphApi/PostGraphOptions.cs, arangodb-net-standard/GraphApi/PostGraphResult.cs
=> Implement Graph List all

arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs
=> Fix GetCollectionProperties test failure with ArangoDB 3.4.6

arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTest.cs, arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs, arangodb-net-standard/DatabaseApi/GetDatabasesResponse.cs
=> Rename response model for GetDatabasesAsync.

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/GraphApiClientTestFixture.cs, arangodb-net-standard/GraphApi/DeleteGraphBody.cs, arangodb-net-standard/GraphApi/DeleteGraphQuery.cs, arangodb-net-standard/GraphApi/DeleteGraphResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Add DeleteGraphAsync

arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTest.cs, arangodb-net-standard/DatabaseApi/CurrentDatabaseInfo.cs, arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs, arangodb-net-standard/DatabaseApi/GetDatabaseInfoResponse.cs, project/roadmap.md
=> Add endpoint to get current database information

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GetGraphResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Add GetGraphAsync

arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PostGraphCreatedGraph.cs, arangodb-net-standard/GraphApi/PostGraphResponse.cs
=> Implement properties of PostGraphResponse model

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GetVertexCollectionsResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Implement endpoint to list vertex collections (GET/_api/gharial/{graph}/vertex)

arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs, arangodb-net-standard/CollectionApi/CollectionApiClient.cs, arangodb-net-standard/CollectionApi/PutCollectionPropertyBody.cs, arangodb-net-standard/CollectionApi/PutCollectionPropertyOptions.cs, arangodb-net-standard/CollectionApi/PutCollectionPropertyResponse.cs
=> Add put collection properties async

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Complete GetGraphs Async

arangodb-net-standard/ApiClientBase.cs, arangodb-net-standard/CollectionApi/CollectionApiClient.cs, arangodb-net-standard/CursorApi/CursorApiClient.cs, arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs, arangodb-net-standard/DocumentApi/DocumentApiClient.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs
=> Remove parameters for null value and camelcase from deserialization method.

arangodb-net-standard/CollectionApi/CollectionApiClient.cs, arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs, arangodb-net-standard/DocumentApi/DocumentApiClient.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/TransactionApi/TransactionApiClient.cs
=> UrlEncode paths and query params

arangodb-net-standard/CursorApi/CursorApiClient.cs, arangodb-net-standard/CursorApi/DeleteCursorResponse.cs
=> Implement properties of DeleteCursorResponse.

project/roadmap.md
=> Remove PUT/_api/simple/all-keys from requirements

arangodb-net-standard/CursorApi/CursorApiClient.cs
=> UrlEncode Cursor API Client

arangodb-net-standard.Test/ApiClientTestFixtureBase.cs, arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTest.cs, arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTestFixture.cs, arangodb-net-standard/DatabaseApi/DatabaseApiClient.cs, arangodb-net-standard/DatabaseApi/DeleteDatabaseResponse.cs, project/roadmap.md
=> Add test and refactor Delete Database Async

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/Graph.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PostGraphEdgeBody.cs, arangodb-net-standard/GraphApi/PostGraphEdgeDefinitionGraph.cs, arangodb-net-standard/GraphApi/PostGraphEdgeResponse.cs, project/roadmap.md
=> Feature post graph edge async

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/DeleteEdgeDefinitionGraph.cs, arangodb-net-standard/GraphApi/DeleteEdgeDefinitionQuery.cs, arangodb-net-standard/GraphApi/DeleteEdgeDefinitionResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Add DeleteEdgeDefinitionAsync

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/DeleteVertexCollectionGraph.cs, arangodb-net-standard/GraphApi/DeleteVertexCollectionQuery.cs, arangodb-net-standard/GraphApi/DeleteVertexCollectionResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Add DeleteVertexCollectionAsync

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/Models/GetVertexMockModel.cs, arangodb-net-standard/GraphApi/GetVertexQuery.cs, arangodb-net-standard/GraphApi/GetVertexResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs
=> Add GetVertexAsync

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/Models/DeleteGraphEdgeMockModel.cs, arangodb-net-standard/GraphApi/DeleteGraphEdgeQuery.cs, arangodb-net-standard/GraphApi/DeleteGraphEdgeResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Add DeleteGraphEdgeAsync

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs
=> Rename GraphApiClient methods to remove extra Graph mention

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs
=> Fix CI build failure

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/Models/DeleteVertexMockModel.cs, arangodb-net-standard/GraphApi/DeleteVertexQuery.cs, arangodb-net-standard/GraphApi/DeleteVertexResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs
=> Add DeleteVertexAsync

arangodb-net-standard/ArangoDBNetStandard.csproj, contributing.md
=> Add project properties for package generation and document how to

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PutGraphEdgeBody.cs, arangodb-net-standard/GraphApi/PutGraphEdgeQuery.cs, arangodb-net-standard/GraphApi/PutGraphEdgeResponse.cs, arangodb-net-standard/GraphApi/PutGraphEdgeResult.cs, project/roadmap.md
=> Add PutGraphEdgeAsync

arangodb-net-standard/GraphApi/PutGraphEdgeResult.cs
=> Fix properties of PutGraphEdgeResult

arangodb-net-standard.Test/Serialization/JsonNetApiClientSerializationTest.cs, arangodb-net-standard/ApiClientBase.cs, arangodb-net-standard/ArangoDBClient.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/Serialization/IApiClientSerialization.cs, arangodb-net-standard/Serialization/JsonNetApiClientSerialization.cs
=> Rename serialization methods and fix build.

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PostGraphQuery.cs
=> Expose query parameters for PostGraphAsync.

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/GetGraphEdgeQuery.cs, arangodb-net-standard/GraphApi/GetGraphEdgeResponse.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, project/roadmap.md
=> Implement GetEdgeAsync GET/_api/gharial/{graph}/edge/{collection}/{edge}

project/roadmap.md
=> Add check to list for HeadDocRead

project/roadmap.md
=> Check off GET, DELETE and POST vertex checklist items.

arangodb-net-standard/Transport/Http/HttpApiTransport.cs
=> Remove extra slash in transport base URL.

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/Models/PatchEdgeMockModel.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PatchEdgeQuery.cs, arangodb-net-standard/GraphApi/PatchEdgeResponse.cs, arangodb-net-standard/GraphApi/PatchEdgeresult.cs, project/roadmap.md
=> Add PatchEdgeAsync

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/GraphApi/Models/PutVertexMockModel.cs, arangodb-net-standard/GraphApi/GraphApiClient.cs, arangodb-net-standard/GraphApi/PutVertexQuery.cs, arangodb-net-standard/GraphApi/PutVertexResponse.cs, arangodb-net-standard/GraphApi/PutVertexResult.cs, project/roadmap.md
=> Add PutVertexAsync

arangodb-net-standard/DocumentApi/DocumentApiClient.cs
=> Add comments for T and U types of patch endpoints.

arangodb-net-standard.Test/Docs/UsageTest.cs, arangodb-net-standard.Test/Docs/UsageTestFixture.cs, arangodb-net-standard/ArangoDBNetStandard.csproj, arangodb-net-standard/Docs/usage.md, readme.md
=> Create dedicated usage documentation and update readme.

arangodb-net-standard/CollectionApi/Models/GetCollectionsQuery.cs, arangodb-net-standard/CollectionApi/Models/PostCollectionQuery.cs, arangodb-net-standard/DocumentApi/Models/PostDocumentsQuery.cs, arangodb-net-standard/GraphApi/Models/DeleteEdgeQuery.cs, arangodb-net-standard/GraphApi/Models/DeleteGraphQuery.cs, arangodb-net-standard/GraphApi/Models/GetEdgeQuery.cs, arangodb-net-standard/GraphApi/Models/PostEdgeQuery.cs
=> Change public ToQueryString methods to be internal

arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard/GraphApi/Models/PostGraphBody.cs
=> Add orphanCollections property in PostGraphBody

arangodb-net-standard.Test/AqlFunctionApi/AqlFunctionApiClientTest.cs, arangodb-net-standard.Test/AqlFunctionApi/AqlFunctionApiClientTestFixture.cs, arangodb-net-standard/AqlFunctionApi/AqlFunctionApiClient.cs, arangodb-net-standard/AqlFunctionApi/IAqlFunctionApiClient.cs, arangodb-net-standard/AqlFunctionApi/Models/AqlFunctionResult.cs, arangodb-net-standard/AqlFunctionApi/Models/DeleteAqlFunctionQuery.cs, arangodb-net-standard/AqlFunctionApi/Models/DeleteAqlFunctionResponse.cs, arangodb-net-standard/AqlFunctionApi/Models/GetAqlFunctionsQuery.cs, arangodb-net-standard/AqlFunctionApi/Models/GetAqlFunctionsResponse.cs, arangodb-net-standard/AqlFunctionApi/Models/PostAqlFunctionBody.cs, arangodb-net-standard/AqlFunctionApi/Models/PostAqlFunctionResponse.cs, arangodb-net-standard/ArangoDBClient.cs, project/roadmap.md
=> Add API client for AQL user functions.

readme.md
=> Add link to nuget under Installation in readme.

arangodb-net-standard/ArangoDBNetStandard.csproj
=> Add arangodb-net-standard as tag for nuget package.

.circleci/config.yml
=> Add tests of ArangoDB 3.6.3

arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs, arangodb-net-standard/CursorApi/Models/CursorResponsePlan.cs
=> Make Initialize property optional in execution plan.

arangodb-net-standard/ArangoDBNetStandard.csproj
fix #209
Add the `GenerateDocumentationFile` element in `.csproj`.
As documented in https://docs.microsoft.com/en-us/dotnet/csharp/codedoc
=> Turn on XML documentation file generation in csproj.

.circleci/config.yml
=> Use ArangoDB 3.4.9 and 3.5.5 in circleci.

arangodb-net-standard/DocumentApi/Models/DeleteDocumentsDocumentResponse.cs, arangodb-net-standard/DocumentApi/Models/PostDocumentsDocumentResponse.cs
=> Remove unused Code property from response models.

arangodb-net-standard/ArangoDBNetStandard.csproj
=> Remove reference to Microsoft.AspNet.WebApi.Client.

arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs, arangodb-net-standard/DocumentApi/DocumentApiClient.cs
#216 
Add test for Robin's PR https://github.com/Actify-Inc/arangodb-net-standard/pull/234 and fix formatting.
=> Get multiple docs

arangodb-net-standard/TransactionApi/ITransactionApiClient.cs, arangodb-net-standard/TransactionApi/TransactionApiClient.cs
=> Add an interface for the transactions API client.

arangodb-net-standard/ArangoDBClient.cs
=> Move APIs instantiation logic into separate method.

arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs, arangodb-net-standard/DocumentApi/Models/PatchDocumentsResponse.cs
=> Add ErrorMessage property in PatchDocumentsResponse.

arangodb-net-standard.Test/ApiClientTestFixtureBase.cs, arangodb-net-standard.Test/UserApi/UserApiClientTest.cs, arangodb-net-standard.Test/UserApi/UserApiClientTestFixture.cs, arangodb-net-standard/ApiClientBase.cs, arangodb-net-standard/ArangoDBClient.cs, arangodb-net-standard/UserApi/IUserApiClient.cs, arangodb-net-standard/UserApi/Models/PostUserBody.cs, arangodb-net-standard/UserApi/Models/PostUserResponse.cs, arangodb-net-standard/UserApi/UserApiClient.cs
=> Feature create user

arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs, arangodb-net-standard/CursorApi/Models/PutCursorResponse.cs
=> Fix Code property of PutCursorResponse.

arangodb-net-standard/ArangoDBClient.cs, arangodb-net-standard/IArangoDBClient.cs
=> Add IArangoDBClient interface. Fixes #296

.circleci/config.yml
=> Build and run tests with release configuration.

.circleci/config.yml
=> Add a step in circle CI config to run tests against arangodb 3.7

arangodb-net-standard.Test/ApiClientTestFixtureBase.cs, arangodb-net-standard.Test/Transport/Http/HttpApiTransportTest.cs, contributing.md
=> Add support for ARANGO_PORT env variable in tests.

.circleci/config.yml, arangodb-net-standard.Test/ArangoDBNetStandardTest.csproj
Updated .Net SDK docker image from 2.2 to 3.1
=> Update .Net SDK to 3.1 for docker image of CI.

arangodb-net-standard/CollectionApi/CollectionApiClient.cs, arangodb-net-standard/CollectionApi/Models/CollectionKeyOptions.cs, arangodb-net-standard/CollectionApi/Models/GetCollectionPropertiesResponse.cs, arangodb-net-standard/CollectionApi/Models/GetCollectionResponse.cs, arangodb-net-standard/CollectionApi/Models/PostCollectionBody.cs, arangodb-net-standard/CollectionApi/Models/PostCollectionResponse.cs, arangodb-net-standard/TransactionApi/TransactionApiClient.cs
Based on top of https://github.com/Actify-Inc/arangodb-net-standard/pull/308
=> Add doc comments to various collection API classes

arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs, arangodb-net-standard/CursorApi/Models/CursorResponse.cs, arangodb-net-standard/CursorApi/Models/ICursorResponse.cs, arangodb-net-standard/CursorApi/Models/PutCursorResponse.cs
=> Create a common interface for POST and PUT cursor responses.

.circleci/config.yml
=> Run tests against ArangoDB 3.8

.circleci/config.yml
=> Use arangodb image 3.8.5.1 for 3.8 tests.

ChangeLog.md
Amended changelog file to accommodate team feedback from https://github.com/ArangoDB-Community/arangodb-net-standard/pull/369#pullrequestreview-958509591
Removed version numbers since we have not yet released these features. We will add the new version 1.1.0 when we release.
=> Amended changelog file

arangodb-net-standard/AqlFunctionApi/Models/PostExplainAqlQueryResponseIndex.cs, arangodb-net-standard/IndexApi/Models/IndexResponseBase.cs
=> Fix type of selectivity estimate in responses.

arangodb-net-standard/CollectionApi/Models/PostCollectionResponse.cs
- Added these two properties to PostCollectionResponse
- Solved #294
=> Added WriteConcern and ReplicationFactor to PostCollectionResponse

arangodb-net-standard/DocumentApi/DocumentApiClient.cs, arangodb-net-standard/DocumentApi/IDocumentApiClient.cs
=> Overloaded PatchDocumentAsync and PatchDocumentsAsync

arangodb-net-standard/DatabaseApi/Models/PostDatabaseBody.cs, arangodb-net-standard/DatabaseApi/Models/PostDatabaseOptions.cs
Added a new PostDatabaseOptions class enable cluster options when creating new databases. Solves #293
=> Added PostDatabaseOptions

arangodb-net-standard/CursorApi/Models/CursorResponseStats.cs
See https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#cursor-api
=> 3.10: Added properties to CursorResponseStats

arangodb-net-standard/AnalyzerApi/Models/Analyzer.cs, arangodb-net-standard/AnalyzerApi/Models/AnalyzerProperties.cs, arangodb-net-standard/ViewApi/Models/SearchAliasIndex.cs, arangodb-net-standard/ViewApi/Models/SearchAliasIndexOperation.cs, arangodb-net-standard/ViewApi/Models/SortCompressionTypes.cs, arangodb-net-standard/ViewApi/Models/ViewDetails.cs, arangodb-net-standard/ViewApi/Models/ViewTypes.cs
1) `offset` Analyzer feature:
https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#offset-analyzer-feature
2) `minhash` Analyzer:
https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#minhash-analyzer
https://www.arangodb.com/docs/3.11/analyzers.html#minhash
3) New view type: `search-alias`
https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#search-alias-views
4) `nearest_neighbors` Analyzer:
https://www.arangodb.com/docs/stable/analyzers.html#nearest_neighbors
5) `classification` Analyzer:
https://www.arangodb.com/docs/stable/analyzers.html#classification
=> 3.10: ArangoSearch changes

arangodb-net-standard/CollectionApi/Models/ComputedValue.cs, arangodb-net-standard/CollectionApi/Models/GetCollectionPropertiesResponse.cs, arangodb-net-standard/CollectionApi/Models/PostCollectionBody.cs, arangodb-net-standard/CollectionApi/Models/PostCollectionResponse.cs
Added ComputedValue class and ComputedValues property to PostCollectionBody, PostCollectionResponse and GetCollectionPropertiesResponse.
For reference see:
https://github.com/arangodb/docs/blob/main/3.10/data-modeling-documents-computed-values.md
https://www.arangodb.com/docs/devel/data-modeling-documents-computed-values.html#computed-value-expressions
=> 310: Implementation of Computed Values

arangodb-net-standard/ArangoDBNetStandard.csproj
Updated csproj to version 1.2.0
=> Updated csproj to the correct version.

arangodb-net-standard/ArangoDBNetStandard.csproj
This should be the last commit required to release 1.3.0
=> Update csproj version to 1.3.0

arangodb-net-standard/ArangoDBNetStandard.csproj
A commit to update the version before releasing a 1.3.1 patch release.
=> Update csproj version to 1.3.1

arangodb-net-standard/IndexApi/IndexApiClient.cs
There were some errors in the usage of async methods that had to fixed in `PostInvertedIndexAsync()`
=> Fixed Errors in PostInvertedIndexAsync

arangodb-net-standard.Test/AdminApi/AdminApiClientTest.cs, arangodb-net-standard.Test/AnalyzerApi/AnalyzerApiClientTest.cs, arangodb-net-standard.Test/AqlFunctionApi/AqlFunctionApiClientTestFixture.cs, arangodb-net-standard.Test/BulkOperationsApi/BulkOperationsApiClientTest.cs, arangodb-net-standard.Test/CollectionApi/CollectionApiClientTest.cs, arangodb-net-standard.Test/CursorApi/CursorApiClientTest.cs, arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTest.cs, arangodb-net-standard.Test/DatabaseApi/DatabaseApiClientTestFixture.cs, arangodb-net-standard.Test/DocumentApi/DocumentApiClientTest.cs, arangodb-net-standard.Test/GraphApi/GraphApiClientTest.cs, arangodb-net-standard.Test/IndexApi/IndexApiClientTest.cs, arangodb-net-standard.Test/ViewApi/ViewApiClientTest.cs, arangodb-net-standard/AnalyzerApi/IAnalyzerApiClient.cs, arangodb-net-standard/ArangoDBClient.cs, arangodb-net-standard/IArangoDBClient.cs, arangodb-net-standard/IndexApi/IIndexApiClient.cs
Use abstractions not implementations
=> Use interfaces instead of implementation for each API client in IArangoDBClient

arangodb-net-standard/ArangoDBNetStandard.csproj
A commit to update the version before releasing 2.0.0, a major release containing a bug fix with breaking changes.
=> Update csproj version to 2.0.0

arangodb-net-standard/ArangoDBNetStandard.csproj
A commit to update the version before releasing 2.0.1, a patch release containing a single bug fix.
=> Update csproj version to 2.0.1

arangodb-net-standard/ArangoDBNetStandard.csproj
Update csproj version to 3.0.0 in preparation for release.
=> Update csproj version to 3.0.0.

arangodb-net-standard/ArangoDBNetStandard.csproj
A commit to update the version before releasing 3.0.1, a patch release containing the following bug fixes:
- https://github.com/ArangoDB-Community/arangodb-net-standard/pull/491
- https://github.com/ArangoDB-Community/arangodb-net-standard/pull/495
=> Update csproj version to 3.0.1

arangodb-net-standard/ArangoDBNetStandard.csproj
A commit to update the version before releasing 3.1.0, a minor release containing bug fixes and minor changes for ArangoDB 3.12
Note: I had planned to create a patch release in Feb, but never got around doing that: #500
=> Update csproj version to 3.1.0
